//! Streaming GTCRN tests — shape verification + state-dict round-trip (default)
//! + parity against the offline model's frame-by-frame output (heavy).

use svod_dtype::DType;
use svod_tensor::Tensor;

use crate::gtcrn::{GtcrnStream, GtcrnStreamJit};
use crate::jit::InputSpec;
use crate::state::HasStateDict;

fn get_shape(tensor: &Tensor) -> Vec<usize> {
    tensor.uop().shape().unwrap().unwrap().iter().map(|s| s.as_const().unwrap()).collect()
}

/// Build the symbolic streaming graph on random weights with T=1 and verify
/// the output + all recycled cache shapes without realizing. Catches axis /
/// cache-slicing / permute bugs across the whole streaming graph in ms.
#[test]
fn stream_forward_shape() {
    let model = GtcrnStream::with_random_weights();
    let (conv_caches, tra_caches, inter_caches) = model.zero_caches();

    // Single-frame spec: (1, 257, 1, 2).
    let spec = Tensor::zeros(&[1, 257, 1, 2], DType::Float32).unwrap();

    let (enh, new_conv, new_tra, new_inter) =
        model.forward_stream(&spec, &conv_caches, &tra_caches, &inter_caches).expect("forward_stream");

    // Output: (1, 257, 1, 2).
    assert_eq!(get_shape(&enh), vec![1, 257, 1, 2], "enhanced spec shape");

    // Encoder conv caches: (1, 16, 2*d, 33) for d=1,2,5 → (1,16,2,33),(1,16,4,33),(1,16,10,33).
    assert_eq!(get_shape(&new_conv.encoder[0]), vec![1, 16, 2, 33], "conv_en[0] (d=1)");
    assert_eq!(get_shape(&new_conv.encoder[1]), vec![1, 16, 4, 33], "conv_en[1] (d=2)");
    assert_eq!(get_shape(&new_conv.encoder[2]), vec![1, 16, 10, 33], "conv_en[2] (d=5)");

    // Decoder conv caches: reversed dilations d=5,2,1.
    assert_eq!(get_shape(&new_conv.decoder[0]), vec![1, 16, 10, 33], "conv_de[0] (d=5)");
    assert_eq!(get_shape(&new_conv.decoder[1]), vec![1, 16, 4, 33], "conv_de[1] (d=2)");
    assert_eq!(get_shape(&new_conv.decoder[2]), vec![1, 16, 2, 33], "conv_de[2] (d=1)");

    // TRA caches: (1, 16) each.
    for (i, c) in new_tra.encoder.iter().enumerate() {
        assert_eq!(get_shape(c), vec![1, 16], "tra_en[{i}]");
    }
    for (i, c) in new_tra.decoder.iter().enumerate() {
        assert_eq!(get_shape(c), vec![1, 16], "tra_de[{i}]");
    }

    // Inter caches: (33, 16) each.
    for (i, c) in new_inter.caches.iter().enumerate() {
        assert_eq!(get_shape(c), vec![33, 16], "inter[{i}]");
    }
}

/// Emit the stream model's state dict and reload it into a fresh model. Verifies
/// the key layout round-trips (including the flipped transpose-conv depth weights).
#[test]
fn stream_state_dict_round_trip() {
    let model = GtcrnStream::with_random_weights();
    let sd = model.state_dict("");

    // Representative keys across all block types.
    let expected_keys = [
        "erb.erb_fc.weight",
        "encoder.en_convs.0.conv.weight",
        "encoder.en_convs.0.conv.bias",
        "encoder.en_convs.2.depth_conv.weight",
        "encoder.en_convs.2.tra.att_gru.weight_ih_l0",
        "dpgrnn1.intra_rnn.rnn1_f.weight_ih_l0",
        "dpgrnn1.inter_rnn.rnn1_f.weight_ih_l0",
        "decoder.de_convs.0.depth_conv.weight",
        "decoder.de_convs.0.tra.att_gru.weight_ih_l0",
        "decoder.de_convs.4.conv.weight",
    ];
    for key in &expected_keys {
        assert!(sd.contains_key(*key), "missing key: {key}");
    }

    // Reload into a fresh model.
    let mut model2 = GtcrnStream::with_random_weights();
    model2.load_state_dict(&sd, "").expect("reload");

    // Verify a tensor round-trips.
    let sd2 = model2.state_dict("");
    let w1 = sd.get("encoder.en_convs.2.depth_conv.weight").unwrap();
    let w2 = sd2.get("encoder.en_convs.2.depth_conv.weight").unwrap();
    assert_eq!(get_shape(w1), get_shape(w2), "depth_conv weight shape mismatch");
}

/// Run the streaming model frame-by-frame on the golden spec and compare to the
/// PyTorch `StreamGTCRN` output (generated by `convert_gtcrn.py --stream-golden`).
///
/// The JIT plan is compiled once (T=1 baked in) and the 14 recurrent caches
/// recycle on-device via the assign-back idiom between `execute()` calls. Each
/// frame's input is sliced along the T axis of the `(1, F, T, C)` golden (frames
/// are strided in the flat buffer, not contiguous), and each output frame is
/// compared against the identically T-sliced `stream_output_crop`.
///
/// ```text
/// SVOD_GTCRN=$PWD/data/gtcrn cargo test -p svod-model --lib gtcrn::stream --release -- --ignored
/// ```
#[test]
#[ignore = "heavy: real GTCRN weights + PyTorch stream golden (local or HF Hub download)"]
fn streaming_matches_pytorch_stream() {
    use std::path::PathBuf;

    fn resolve_file(name: &str) -> PathBuf {
        if let Ok(dir) = std::env::var("SVOD_GTCRN") {
            let p = PathBuf::from(dir).join(name);
            if p.exists() {
                return p;
            }
        }
        let p = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../data/gtcrn").join(name);
        if p.exists() {
            return p;
        }
        let api = hf_hub::api::sync::Api::new().expect("HF Hub API");
        let repo = hf_hub::Repo::with_revision("vpermilp/gtcrn".into(), hf_hub::RepoType::Model, "main".into());
        api.repo(repo).get(name).unwrap_or_else(|_| panic!("download {name} from vpermilp/gtcrn"))
    }

    let weights = resolve_file("gtcrn.safetensors");
    let golden_path = resolve_file("golden_stream.safetensors");

    let model = GtcrnStream::from_safetensors(&weights).expect("load stream model");
    let golden = crate::state::load_safetensors(&golden_path).expect("load golden");

    // The streaming golden uses spec_crop (same as offline) and stream_output_crop
    // (from the PyTorch StreamGTCRN, frame-by-frame). Both are (1, F, T, C) — we
    // slice each frame along T below to compare frame-by-frame.

    // The spec_crop golden is laid out (1, F=257, T=24, C=2) row-major, so the
    // 24 frames are NOT contiguous in the flat buffer — frame i lives at
    // strided offsets (f*48 + i*2 + c). Slice the T axis in the graph (not the
    // flat buffer) to extract each frame correctly, matching the PyTorch
    // `spec_crop[:, :, i:i+1, :]`.
    let spec_full = crate::state::get_tensor(&golden, "spec_crop").unwrap().clone();
    let n_frames = 24;
    let frame_tensors: Vec<Vec<f32>> = (0..n_frames)
        .map(|i| {
            use svod_ir::SInt;
            let mut f =
                spec_full.clone().try_shrink([None, None, Some((SInt::Const(i), SInt::Const(i + 1))), None]).unwrap();
            f.realize().unwrap();
            f.as_vec::<f32>().unwrap()
        })
        .collect();

    // Prepare the JIT once with T=1 (compile once), then execute per frame.
    // The caches recycle on-device via the assign-back idiom — no graph
    // accumulation across frames.
    let mut jit = GtcrnStreamJit::new(model);

    // Build the InputSpec array: spec (host-visible) + all caches (device-local).
    let tra_hidden = 16; // half*2 = (C_NET/2)*2
    jit.prepare_with_config(
        InputSpec::f32(&[1, 257, 1, 2]),
        InputSpec::f32(&[1, 16, 2, 33]).device_local(),  // conv_en0 (d=1)
        InputSpec::f32(&[1, 16, 4, 33]).device_local(),  // conv_en1 (d=2)
        InputSpec::f32(&[1, 16, 10, 33]).device_local(), // conv_en2 (d=5)
        InputSpec::f32(&[1, 16, 10, 33]).device_local(), // conv_de0 (d=5)
        InputSpec::f32(&[1, 16, 4, 33]).device_local(),  // conv_de1 (d=2)
        InputSpec::f32(&[1, 16, 2, 33]).device_local(),  // conv_de2 (d=1)
        InputSpec::f32(&[1, tra_hidden]).device_local(), // tra_en0
        InputSpec::f32(&[1, tra_hidden]).device_local(), // tra_en1
        InputSpec::f32(&[1, tra_hidden]).device_local(), // tra_en2
        InputSpec::f32(&[1, tra_hidden]).device_local(), // tra_de0
        InputSpec::f32(&[1, tra_hidden]).device_local(), // tra_de1
        InputSpec::f32(&[1, tra_hidden]).device_local(), // tra_de2
        InputSpec::f32(&[33, 16]).device_local(),        // inter0
        InputSpec::f32(&[33, 16]).device_local(),        // inter1
        &svod_tensor::PrepareConfig::from_env(),
    )
    .expect("JIT prepare");

    // Zero-init all caches on-device.
    let zeros_tra = vec![0.0f32; tra_hidden];
    let zeros_inter = vec![0.0f32; 33 * 16];
    let zero_conv_1 = vec![0.0f32; 16 * 2 * 33];
    let zero_conv_2 = vec![0.0f32; 16 * 4 * 33];
    let zero_conv_5 = vec![0.0f32; 16 * 10 * 33];
    {
        macro_rules! zero_cache {
            ($getter:ident, $data:expr) => {{
                jit.$getter().unwrap().copyin(bytemuck::cast_slice(&$data)).unwrap();
            }};
        }
        zero_cache!(conv_en0_mut, zero_conv_1);
        zero_cache!(conv_en1_mut, zero_conv_2);
        zero_cache!(conv_en2_mut, zero_conv_5);
        zero_cache!(conv_de0_mut, zero_conv_5);
        zero_cache!(conv_de1_mut, zero_conv_2);
        zero_cache!(conv_de2_mut, zero_conv_1);
        zero_cache!(tra_en0_mut, zeros_tra);
        zero_cache!(tra_en1_mut, zeros_tra);
        zero_cache!(tra_en2_mut, zeros_tra);
        zero_cache!(tra_de0_mut, zeros_tra);
        zero_cache!(tra_de1_mut, zeros_tra);
        zero_cache!(tra_de2_mut, zeros_tra);
        zero_cache!(inter0_mut, zeros_inter);
        zero_cache!(inter1_mut, zeros_inter);
    }

    // want_full is (1, F=257, T=24, C=2) row-major — frames are NOT contiguous
    // in the flat buffer. Extract each frame along T (matching the input slicing)
    // so got[i] and want[i] are both single-frame (1,257,1,2) flat buffers.
    let want_full = crate::state::get_tensor(&golden, "stream_output_crop").unwrap().clone();
    let want_frame = |i: usize| -> Vec<f32> {
        use svod_ir::SInt;
        let mut f =
            want_full.clone().try_shrink([None, None, Some((SInt::Const(i), SInt::Const(i + 1))), None]).unwrap();
        f.realize().unwrap();
        f.as_vec::<f32>().unwrap()
    };

    let mut max_delta = 0.0f32;
    let mut peak = 0.0f32;
    for frame in 0..n_frames {
        // Write one frame (correctly sliced along T) into the spec input buffer.
        jit.spec_mut().unwrap().copyin(bytemuck::cast_slice(&frame_tensors[frame])).unwrap();

        // Execute (caches recycle on-device).
        jit.execute().unwrap();

        // Read the enhanced frame and compare against the T-sliced golden frame.
        let out = jit.enh().unwrap();
        let got_slice: &[f32] = out.as_slice().unwrap();
        let want_slice = want_frame(frame);
        assert_eq!(got_slice.len(), want_slice.len(), "frame {frame} length mismatch");
        for (a, b) in got_slice.iter().zip(&want_slice) {
            max_delta = max_delta.max((a - b).abs());
            peak = peak.max(b.abs());
        }
    }

    let rel = max_delta / peak.max(1e-6);
    assert!(rel < 1e-3, "streaming vs PyTorch: max |delta| = {max_delta:.6} (rel {rel:.2e}, peak {peak:.2})");
}
